language: node_js
node_js:
- '10'
matrix:
  include:
  - name: Test with Ice 3.6.4
    env: SLICE2JS=slice2js@3.6.4
  - name: Test With Ice 3.7.1
    env: SLICE2JS=slice2js@3.7.1
  - name: Test With Ice 3.7 HEAD
    env: SLICE2JS=zeroc-ice/npm-slice2js#3.7
install:
- npm install $SLICE2JS
script:
- npx mocha tests/test.js
notifications:
  slack:
    secure: WqIiOTbH2Tm2AoKaDNO9owUn5p2LTJhH7qYZBOKttsAnkfPgEdJDfUkgMVT3jtv1Hg4+pW3x1dnrYWohM2bPclFgOGh5/flcMbx1sbPacoZws9Td5WTj7FjbPaghEzlQ8ZL0IMmYEpRE4U3pdi2OXdl8aqOnxOB7IH9bAyFO59w=
